<?php
//==================================
//SECTION B Questions
//==================================
$section_b = array("I had a threat to my life",
"I had a threat to member of family",
"I almost died due the threat",
"I was beaten and harassed",
"I had death of a family life member",
"I was forced to seperate/leave family members",
"I almost died",
"The police and military were following/beating me",
"I was harassed by the police",
"I was hungry all the time", 
"I didn't have food and water", 
"I had no place to live", 
"I had nothing", 
"I had trouble with housing", 
"I had trouble getting a job", 
"I had trouble with my papers", 
"I was not accepted because of my political/sexual orientation", 
"Someone raped/assaulted me before age 18 years", 
"I was forced to have sex since", 
"I was forced to sell my body for money", 
"I was sexually harassed", 
"I was physically beaten all the time", 
"I am rich", 
"I am poor", 
"I am famous", 
"I am comfortable"
);

$section_c = array( "A1" => array("Been feeling perfectly well and in good health" => array("Better than usual", "Same as usual", "Worse than usual", "Much more than usual" )),
 "A2" => array("Been feeling in need of some medicine to pick you up" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "A3" => array("Been feeling run down and out of sorts" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "A4" => array("Felt that you're ill?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "A5" => array("Been getting any pains in your head?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "A6" => array("Been getting a feeling of tightness or pressure in your head?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "A7" => array("Been having hot or cold spells" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "B1" => array("Lost much sleep over worry" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "B2" => array("Had difficulty staying asleep" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "B3" => array("Felt constantly under strain?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "B4" => array("Been getting edgy and bad-tempered?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "B5" => array("Been getting scared or panicky for no good reason?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "B6" => array("Found everything getting on top of you?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "B7" => array("Been feeling nervous and uptight all the time?" => array("Not at All", "No more than usual", "Worse than usual", "Much more than usual" )),
 "C1" => array("Been managing to keep yourself busy and occupied?" => array("More so than usual", "Same as usual", "Rather less than usual", "Much less than usual" )),
 "C2" => array("Been taking longer over the things you do?" => array("Quicker than usual", "Same as usual", "Longer than usual", "Much longer than usual" )),
 "C3" => array("Felt on the whole you were doing things well?" => array("Better than usual", "About the same", "Less well than usual", "Much less well" )),
 "C4" => array("Been satisfied with the way you've carried out your task?" => array("More satisfied", "About the same as usual", "Less satisfied than usual", "Much less satisfied" )),
 "C5" => array("Felt that you're playing a useful part in things?" => array("More so than usual", "Same as usual", "Less useful than usual", "Much less useful" )),
 "C6" => array("Felt capable of making decisions about things?" => array("More so than usual", "Same as usual", "Less so than usual", "Much less capable" )),
 "C7" => array("Been able to enjoy your normal day-to-day activities?" => array("More so than usual", "Same as usual", "Rather less than usual", "Much less than usual" )),
 "D1" => array("Been thinking of yourself as a worthless person?" => array("Not at all", "No more than usual", "Rather more than usual", "Much more than usual" )),
 "D2" => array("Felt that life is entirely hopeless" => array("Not at all", "No more than usual", "Rather more than usual", "Much more than usual" )),
 "D3" => array("Felt that life isn't worth living?" => array("Not at all", "No more than usual", "Rather more than usual", "Much more than usual" )),
 "D4" => array("Thought of the possibility that you might do away with yourself?" => array("Definitely not", "I don't think so", "Has crossed my mind", "Definitely has" )),
 "D5" => array("Found at times you couldn't do anything because your nerves were too bad?" => array("Not at all", "Nomore than usual", "Rather more than usual", "Much more than usual" )),
 "D6" => array("Found yourself wishing you were dead and away from it all?" => array("Not at all", "Nomore than usual", "Rather more than usual", "Much more than usual" )),
 "D7" => array("Found out that the idea of taking your own life kept coming into your mind?" => array("Definitely not", "I don't think so", "Has crossed my mind", "Definitely has" ))
  );
//==================================
//SECTION D Questions
//==================================
$section_d = array(
  "Does your mood often go up and down", 
  "Do you take much notice of what people think",
  "Are you a talkative person",
  "If you say you will do something, do you always keep your promise no matter how incovenient it can be",
  "Do you just feel miserable for no reason?", 
  "Would being in debt worry you?",
  "Are you rather lively",
  "Were you ever greedy by helping yourself to more than your share of anything?",
  "Are you an irritable person?",
  "Would you take drugs which may have strange or dangerous effects?",
  "Do you enjoy meeting people",
  "have you ever blamed someone for doing something you knew was really your fault?",
  "Are your feelings easily hurt?",
  "Do you prefer to go your way rather than act by the rules?",
  "Can you usually let yourself go and enjoy yourself at a lively party?",
  "Are your habits good and desirable ones?",
  "Do you often feel 'fed-up'?",
  "Do good manners and cleanliness matter much to you?",
  "Do you usually take the initiative in making new friends?",
  "Have you ever taken anything(even a pin or a button) that belonged to someone else?",
  "Would you call yourself a nervous person?",
  "Do you think marriage is old-fashioned and should be done away with?",
  "Can you easily get some life to a rather dull party?",
  "Have you ever broken or lost something belonging to someone else?",
  "Are you a worrier?", 
  "Do you enjoy cooperating with others?",
  "Do you intend to keep in the background on social occasions?",
  "Does it worry you if you know there are mistakes in your work?",
  "Have you ever said anything bad or nasty about anyone?",
  "Would you call your self tense or 'highly strung'?",
  "Do you think people spend too much time safeguarding their future with savings and insuarance?",
  "Do you like mixing with people?",
  "As a child, were you ever cheeky to your parents?",
  "Do you worry too long after an embarrassing experience?",
  "Do you try not to be rude to people?",
  "Do you like plenty of bustle and excitement around you?",
  "Have you ever cheated at a game?",
  "Do you suffer from 'nerves'?",
  "Would like other people to be afraid of you?",
  "Have you ever taken advantage of someone?",
  "Are you mostly quite when with other people?",
  "Do you often feel lonely?",
  "Is it better to follow society rule's rather to go your own way?",
  "Do other people think of you as being lively?",
  "Do you always practice what you preach?",
  "Are you always troubled about feelings of guilt?",
  "Do you sometimes put off until tomorrow what you ought to do today?",
  "Can you get a party going?"
);
//==================================
//SECTION E Questions
//==================================
$section_e = array(
  "Foreigners are allowed in this country if they make a contribution",
  "Locals would have higher standards of living if there were no foreigners living in this country",
  "I think foreigners should be given the same opportunities as local citizens",
  "I would date a local",
  "Attacks against foreigners are wrong",
  "Foreigners tend to increase the crime rate in this country",
  "Foreigners take jobs away from locals",
  "This country is letting in too many foreigners",
  "Foreigners bring in possibility of disease",
  "Immigration in this country is out of control",
  "Interacting with locals makes me feel uneasy",
  "I would welcome interactions with locals"

);
//==================================
//SECTION F Questions
//==================================
$section_f = array(
  "Repeated, disturbing memories, thoughts, or images of a stressful experience from the past?",
  "Repeated, disturbing dreams of a stressful experience from the past?",
  "Suddenly acting or feeling as if a stressful experience were happening again(As if you were reliving it)?",
  "Feeling very upset when something reminded you of a stressful experience from the past?",
  "having physical reactions(e.g heart pounding, trouble breathing,or sweating) when something reminded you of a stressful experience from the past?",
  "Avoid thinking about or talking about a stressful experience from the past or avoid feeling related to it?",
  "Avoid activities or situations because they remind you of a stressful experience in the past?",
  "Trouble remembering important parts of a stressful from the past?",
  "Loss of interest in things that you used to enjoy?",
  "Feeling distant or cut off from other people?",
  "Feeling emotionally numb or being unable to have loving feelings for those close to you?",
  "Feeling as if your future will somehow be cut short?",
  "Trouble falling or staying asleep?",
  'Feeling irritable or having angry outbursts?',
  "Having difficulty concentrating?",
  "Being 'super alert' or watchful on guard?",
  "Feeling jumpy or easily startled?"

);
//==================================
//SECTION G Questions
//==================================
$section_g = array(
  "I have been turning to work or other activities to take my mind off things",
  "I've been concentrating my efforts on doing something about the situation I am in",
  "I've been saying to myself 'this isn't real'",
  "I've been using alcohol or other drugs to make myself feel better",
  "I've been getting emotional support from others",
  "I've been giving up trying to deal with it",
  "I've been taking action to try to make the situation better",
  "I've been refusing to believe that it has happened",
  "I've been saying things to let my unpleasant feelings escape",
  "I've been getting help and advice from other people",
  "I've been using alcohol or other drugs to help me get through it ",
  "I've been trying to see it in different light, to make it seem more positive",
  "I've been criticizing myself",
  "I've been trying to come up with a strategy about what to do",
  "I've been getting comfort and understanding from someone",
  "I've been giving up the attempt to cope",
  "I've been looking for something good in what is happening",
  "I've been making jokes about it",
  "I've been doing something to think about it less,such as going to movies,watching TV,reading,sleeping or shopping",
  "I've been accepting the reality that it has happened",
  "I've been expressing my negative feelings",
  "I've been trying to find comfort in my religion or spiritual beliefs",
  "I've been trying to get advice or help from other people about what to do",
  "I've been learning to live with it",
  "I've been thinking hard about what steps to take",
  "I've been blaming myself for things that happened",
  "I've been praying or meditating",
  "I've been making fun of the situation"
);
//==================================
//SECTION H Questions
//==================================
$section_h = array(
  "It is important to this person to think up new ideas and be creative;to do things one's way",
  "It is important to this person to be rich;to have a lot of money and expensive things",
  "Living in secure surroundings is important to this person;to avoid anything that might be dangerous",
  "It is important to this person to have a god time;to 'spoil' oneself",
  "It is important to this person to do something to the good of society",
  "Being very successful is important to this person;to have people recognize one's achievements",
  "Adventure and taking risks is important to this person;to have an exciting life",
  "It is important to this person to always behave properly;to avoid doing anything people would say is wrong",
  "Looking after the environment is important to this person;to care for nature and save life resources",
  "Tradition is important to this person"
);
?>